# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: '0x1CAf5dB59Ac863638467d5A0C61eaf574aCb1d91'
    chainName: rivalz
    coinGeckoId: etherfi-weeths
    collateralAddressOrDenom: '0x917cee801a67f933f2e6b33fc0cd1ed2d5909d88'
    connections:
      - token: sealevel|solanamainnet|93bVs9o8Nq88zxnLWwUAVfN5PXBhCcnV5sfs6AFLno8q
    decimals: 8
    logoURI: /deployments/warp_routes/weETHs/logo.svg
    name: rivalz - solana
    standard: EvmHypCollateral
    symbol: RIZ
  - addressOrDenom: EobBtPkD2oJ4ADCYZ8F2j67S62cRB8VuMMnpBhrhgsRN
    chainName: solanamainnet
    collateralAddressOrDenom: 93bVs9o8Nq88zxnLWwUAVfN5PXBhCcnV5sfs6AFLno8q
    connections:
      - token: rivalz|rivalz|0xef899e92DA472E014bE795Ecce948308958E25A2
    decimals: 8
    logoURI: /deployments/warp_routes/weETHs/logo.svg
    name: Super Symbiotic LRT
    standard: SealevelHypSynthetic
    symbol: RIZ
